#!/usr/bin/env bash
# Start local Antar stack: Postgres + Redis + backend (+ optional mobile).
#
# Usage:
#   ./scripts/development/start-local.sh           # infra + backend + iOS simulator
#   ./scripts/development/start-local.sh --no-mobile
#   ./scripts/development/start-local.sh --android
#   make start
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
LOCAL_DIR="${ROOT}/.local"
mkdir -p "${LOCAL_DIR}"

START_MOBILE=1
MOBILE_PLATFORM=ios

for arg in "$@"; do
  case "${arg}" in
    --no-mobile) START_MOBILE=0 ;;
    --ios) START_MOBILE=1; MOBILE_PLATFORM=ios ;;
    --android) START_MOBILE=1; MOBILE_PLATFORM=android ;;
    -h|--help)
      sed -n '2,10p' "$0"
      exit 0
      ;;
    *)
      echo "Unknown argument: ${arg}" >&2
      echo "Usage: $0 [--no-mobile|--ios|--android]" >&2
      exit 1
      ;;
  esac
done

if [[ -f "${ROOT}/.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "${ROOT}/.env"
  set +a
else
  cp "${ROOT}/.env.example" "${ROOT}/.env"
  echo "Created ${ROOT}/.env from .env.example"
fi

POSTGRES_DB="${POSTGRES_DB:-antar}"
POSTGRES_USER="${POSTGRES_USER:-antar}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-antar}"
POSTGRES_PORT="${POSTGRES_PORT:-5432}"
REDIS_PORT="${REDIS_PORT:-6379}"
SERVER_PORT="${SERVER_PORT:-8080}"

port_listening() {
  lsof -nP -iTCP:"$1" -sTCP:LISTEN >/dev/null 2>&1
}

antar_backend_up() {
  local port="$1"
  curl -sf "http://127.0.0.1:${port}/api/internal/foundation/status" 2>/dev/null \
    | grep -q '"service":"antar-backend"'
}

# Prefer the published port of an already-running Antar Postgres container.
if docker ps --format '{{.Names}}' 2>/dev/null | grep -qx 'antar-postgres'; then
  published="$(docker port antar-postgres 5432/tcp 2>/dev/null | head -1 | awk -F: '{print $NF}')"
  if [[ -n "${published}" ]]; then
    POSTGRES_PORT="${published}"
  fi
elif port_listening "${POSTGRES_PORT}"; then
  if [[ "${POSTGRES_PORT}" == "5432" ]]; then
    echo "Host port 5432 is in use; publishing Antar Postgres on 5435."
    POSTGRES_PORT=5435
  else
    echo "Host port ${POSTGRES_PORT} is already in use." >&2
    echo "Set POSTGRES_PORT in .env to a free port and retry." >&2
    exit 1
  fi
fi

# Prefer the API port already configured for mobile, when present.
if [[ -f "${ROOT}/mobile/.env" ]]; then
  mobile_url="$(
    grep -E '^[[:space:]]*EXPO_PUBLIC_API_BASE_URL=' "${ROOT}/mobile/.env" \
      | tail -1 \
      | cut -d= -f2- \
      | tr -d '[:space:]"'\'''
  )"
  if [[ "${mobile_url}" =~ :([0-9]+)$ ]]; then
    SERVER_PORT="${BASH_REMATCH[1]}"
  fi
fi

if port_listening "${SERVER_PORT}" && ! antar_backend_up "${SERVER_PORT}"; then
  if [[ "${SERVER_PORT}" == "8080" ]]; then
    echo "Host port 8080 is in use; starting Antar backend on 8082."
    SERVER_PORT=8082
    if port_listening "${SERVER_PORT}" && ! antar_backend_up "${SERVER_PORT}"; then
      echo "Host port 8082 is also in use by a non-Antar process." >&2
      echo "Set SERVER_PORT in .env to a free port and retry." >&2
      exit 1
    fi
  else
    echo "Host port ${SERVER_PORT} is in use by a non-Antar process." >&2
    echo "Set SERVER_PORT in .env to a free port and retry." >&2
    exit 1
  fi
fi

export POSTGRES_DB POSTGRES_USER POSTGRES_PASSWORD POSTGRES_PORT REDIS_PORT SERVER_PORT

# Keep root .env aligned so compose and later shells reuse the resolved ports.
python3 - "${ROOT}/.env" "${POSTGRES_PORT}" "${SERVER_PORT}" "${REDIS_PORT}" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1])
postgres_port, server_port, redis_port = sys.argv[2], sys.argv[3], sys.argv[4]
text = path.read_text() if path.exists() else ""
lines = text.splitlines()
keys = {
    "POSTGRES_PORT": postgres_port,
    "SERVER_PORT": server_port,
    "REDIS_PORT": redis_port,
}
seen = set()
out = []
for line in lines:
    if not line.strip() or line.lstrip().startswith("#") or "=" not in line:
        out.append(line)
        continue
    key = line.split("=", 1)[0].strip()
    if key in keys:
        out.append(f"{key}={keys[key]}")
        seen.add(key)
    else:
        out.append(line)
for key, value in keys.items():
    if key not in seen:
        out.append(f"{key}={value}")
path.write_text("\n".join(out) + "\n")
PY

# Keep mobile API URL aligned with the backend port we are about to use.
mkdir -p "${ROOT}/mobile"
if [[ "${MOBILE_PLATFORM}" == "android" ]]; then
  api_host="10.0.2.2"
else
  api_host="localhost"
fi
cat > "${ROOT}/mobile/.env" <<EOF
# Generated by scripts/development/start-local.sh — do not commit.
EXPO_PUBLIC_API_BASE_URL=http://${api_host}:${SERVER_PORT}
EOF

echo "==> Starting Postgres + Redis (Postgres host port ${POSTGRES_PORT})"
(
  cd "${ROOT}"
  docker compose up -d --wait
)

if antar_backend_up "${SERVER_PORT}"; then
  echo "==> Backend already healthy on http://localhost:${SERVER_PORT}"
else
  if port_listening "${SERVER_PORT}"; then
    echo "Port ${SERVER_PORT} is busy but Antar foundation status is not reachable." >&2
    exit 1
  fi

  echo "==> Starting backend on http://localhost:${SERVER_PORT} (profile=local)"
  (
    cd "${ROOT}/backend"
    nohup env POSTGRES_PORT="${POSTGRES_PORT}" REDIS_PORT="${REDIS_PORT}" \
      ./mvnw spring-boot:run \
      -Dspring-boot.run.profiles=local \
      -Dspring-boot.run.arguments=--server.port="${SERVER_PORT}" \
      >"${LOCAL_DIR}/backend.log" 2>&1 &
    echo $! >"${LOCAL_DIR}/backend.pid"
  )

  echo "    Waiting for backend..."
  for _ in $(seq 1 90); do
    if antar_backend_up "${SERVER_PORT}"; then
      break
    fi
    if ! kill -0 "$(cat "${LOCAL_DIR}/backend.pid")" 2>/dev/null; then
      echo "Backend process exited. See ${LOCAL_DIR}/backend.log" >&2
      tail -n 40 "${LOCAL_DIR}/backend.log" >&2 || true
      exit 1
    fi
    sleep 1
  done

  if ! antar_backend_up "${SERVER_PORT}"; then
    echo "Backend did not become healthy in time. See ${LOCAL_DIR}/backend.log" >&2
    tail -n 40 "${LOCAL_DIR}/backend.log" >&2 || true
    exit 1
  fi
  echo "==> Backend ready"
fi

if [[ "${START_MOBILE}" -eq 1 ]]; then
  if [[ ! -d "${ROOT}/mobile/node_modules" ]]; then
    echo "==> Installing mobile dependencies"
    (cd "${ROOT}/mobile" && npm ci)
  fi

  if port_listening 8081; then
    echo "==> Metro already listening on 8081; not starting a second Expo process"
    echo "    Open the Simulator or press i/a in the existing Expo terminal."
  else
    echo "==> Starting Expo (${MOBILE_PLATFORM})"
    (
      cd "${ROOT}/mobile"
      nohup npm run "${MOBILE_PLATFORM}" >"${LOCAL_DIR}/mobile.log" 2>&1 &
      echo $! >"${LOCAL_DIR}/mobile.pid"
    )
    echo "    Mobile logs: ${LOCAL_DIR}/mobile.log"
  fi
fi

echo
echo "Antar local stack is up."
echo "  API:      http://localhost:${SERVER_PORT}"
echo "  Chapters: http://localhost:${SERVER_PORT}/api/v1/scripture/chapters"
echo "  Status:   http://localhost:${SERVER_PORT}/api/internal/foundation/status"
echo "  Postgres: localhost:${POSTGRES_PORT}"
echo "  Stop with: make stop"
echo
